# Generated by Django 4.2.5 on 2024-01-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseStudies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='case_studies_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
