# Generated by Django 4.2.5 on 2024-12-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseStudies', '0002_alter_casestudies_case_studies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='originalname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
