# Generated by Django 4.2.5 on 2024-01-09 11:11

import common.BaseModel
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('originalname', models.CharField(blank=True, max_length=100, null=True)),
                ('contentType', models.CharField(blank=True, max_length=100, null=True)),
                ('alternitivetext', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedIn_url', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=500, null=True)),
                ('vimeo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pinterest_url', models.CharField(blank=True, max_length=500, null=True)),
                ('team_member_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_member_email', models.CharField(blank=True, max_length=200, null=True)),
                ('team_member_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('team_member_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('team_member_about_us', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
