# Generated by Django 4.2.5 on 2025-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_remove_carousel_alternitivetext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeintro',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
