# Generated by Django 4.2.5 on 2025-08-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_carousel_category_clientlogo_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeintro',
            name='alternative_text',
        ),
        migrations.RemoveField(
            model_name='homeintro',
            name='category',
        ),
        migrations.RemoveField(
            model_name='homeintro',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='homeintro',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='homeintro',
            name='path',
        ),
    ]
