# Generated by Django 4.2.5 on 2024-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_rename_imagedescription_clientlogo_client_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carouse_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='client_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
