# Generated by Django 4.2.5 on 2024-12-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_carousel_carouse_position_clientlogo_client_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='originalname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='originalname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
