# Generated by Django 4.2.5 on 2025-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_alter_carousel_originalname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='contentType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='contentType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
