# Generated by Django 4.2.5 on 2025-06-19 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_brochures_contenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsenggRaqForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('cityAddress', models.CharField(blank=True, max_length=1000, null=True)),
                ('stateProvince', models.CharField(blank=True, max_length=1000, null=True)),
                ('natureofProject', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('teams', models.CharField(blank=True, max_length=100, null=True)),
                ('hangout', models.CharField(blank=True, max_length=100, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
