# Generated by Django 4.2.5 on 2025-09-04 07:09

import common.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.file_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternative_text', models.CharField(blank=True, max_length=255, null=True)),
                ('pageType', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_title', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_subTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_descripiton', models.CharField(blank=True, max_length=5000, null=True)),
                ('moreLink', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
