# Generated by Django 4.2.5 on 2025-08-27 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_permission_list', models.JSONField()),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
    ]
