# Generated by Django 4.2.5 on 2024-12-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='about_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careers',
            name='employment_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careers',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='careers',
            name='mode_of_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careers',
            name='no_of_application',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careers',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careers',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
