# Generated by Django 4.2.5 on 2024-12-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careers_about_company_careers_employment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='location',
        ),
    ]
