# Generated by Django 4.2.5 on 2025-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_seo_author_product_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contentType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
