# Generated by Django 4.2.5 on 2025-09-10 14:23

import common.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternative_text', models.CharField(blank=True, max_length=255, null=True)),
                ('category_Label', models.CharField(max_length=50)),
                ('category_Value', models.CharField(blank=True, max_length=50, null=True)),
                ('category_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('readMore_link', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_category',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projectCategoryID', models.CharField(max_length=100)),
                ('projectCategoryName', models.CharField(max_length=50)),
                ('projectCategoryValue', models.CharField(max_length=50)),
                ('projectTitle', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('percentValue', models.CharField(blank=True, max_length=50, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('aboutstitle', models.CharField(blank=True, max_length=50, null=True)),
                ('aboutussubtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('imageDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('projectImage', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('seo_link', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_author', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='realestate.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_projects',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('feature', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='realestate.projects')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_specifications',
            },
        ),
        migrations.CreateModel(
            name='FeatureAndAmenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenitie', models.CharField(blank=True, max_length=5000, null=True)),
                ('feature', models.CharField(blank=True, max_length=5000, null=True)),
                ('googleMap', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_amenities', to='realestate.projects')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_feature_and_amenities',
            },
        ),
    ]
