# Generated by Django 4.2.5 on 2025-08-23 15:55

import common.BaseModel
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('originalname', models.CharField(blank=True, max_length=500, null=True)),
                ('contentType', models.CharField(blank=True, max_length=500, null=True)),
                ('alternitivetext', models.CharField(blank=True, max_length=500, null=True)),
                ('category_Label', models.CharField(max_length=50)),
                ('category_Value', models.CharField(blank=True, max_length=50, null=True)),
                ('category_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('readMore_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureAndAmenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projectID', models.CharField(max_length=100, unique=True)),
                ('amenitie', models.CharField(blank=True, max_length=5000, null=True)),
                ('feature', models.CharField(blank=True, max_length=5000, null=True)),
                ('googleMap', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('idprojectcategories', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('projectLabel', models.CharField(max_length=50)),
                ('projectValue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projectCategoryID', models.CharField(max_length=100)),
                ('projectCategoryName', models.CharField(max_length=50)),
                ('projectCategoryValue', models.CharField(max_length=50)),
                ('projectTitle', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('percentValue', models.CharField(blank=True, max_length=50, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('aboutstitle', models.CharField(blank=True, max_length=50, null=True)),
                ('aboutussubtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('imageDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('userID', models.CharField(max_length=50)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('seo_link', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_author', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projectID', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('feature', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
