# Generated by Django 4.2.5 on 2025-09-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_alter_featureandamenities_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projectCategoryValue',
            new_name='projectStatus',
        ),
    ]
