# Generated by Django 4.2.5 on 2025-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_category_featureandamenities_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_Value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
