# Generated by Django 4.2.5 on 2025-09-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_rename_projectcategoryvalue_projects_projectstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projectCategoryName',
        ),
    ]
