# Generated by Django 4.2.5 on 2025-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_alter_category_category_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
