# Generated by Django 4.2.5 on 2025-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_projectgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
