# Generated by Django 4.2.5 on 2025-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_alter_category_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='seo_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
