# Generated by Django 4.2.5 on 2025-09-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_projectgallery_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectgallery',
            old_name='description',
            new_name='image_description',
        ),
    ]
