# Generated by Django 4.2.5 on 2025-08-23 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_label', models.CharField(blank=True, max_length=100)),
                ('page_url', models.CharField(blank=True, max_length=100, null=True)),
                ('page_isActive', models.BooleanField(default=True)),
                ('is_Parent', models.BooleanField(default=True)),
                ('page_parent_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('page_position', models.IntegerField(default=0)),
                ('is_Admin_menu', models.BooleanField(default=False)),
                ('is_Client_menu', models.BooleanField(default=True)),
                ('is_Maintainer_menu', models.BooleanField(default=False)),
                ('service_menu_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_link', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_author', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
