# Generated by Django 4.2.5 on 2024-01-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedetails',
            name='page_positions',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
