# Generated by Django 4.2.5 on 2024-01-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0003_remove_pagedetails_page_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedetails',
            name='page_position',
            field=models.IntegerField(default=0),
        ),
    ]
