# Generated by Django 4.2.5 on 2024-01-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0004_alter_pagedetails_page_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedetails',
            name='is_Client_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagedetails',
            name='is_SuperAdmin_menu',
            field=models.BooleanField(default=False),
        ),
    ]
