# Generated by Django 4.2.5 on 2024-01-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0005_pagedetails_is_client_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagedetails',
            old_name='is_SuperAdmin_menu',
            new_name='is_Admin_menu',
        ),
    ]
