# Generated by Django 4.2.5 on 2024-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0006_rename_is_superadmin_menu_pagedetails_is_admin_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedetails',
            name='is_Maintainer_menu',
            field=models.BooleanField(default=False),
        ),
    ]
