# Generated by Django 4.2.5 on 2025-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0007_pagedetails_is_maintainer_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedetails',
            name='seo_meta_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagedetails',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pagedetails',
            name='seo_meta_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagedetails',
            name='seo_meta_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagedetails',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
