# Generated by Django 4.2.5 on 2025-05-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0008_pagedetails_seo_meta_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagedetails',
            old_name='seo_meta_author',
            new_name='seo_author',
        ),
        migrations.RenameField(
            model_name='pagedetails',
            old_name='seo_meta_description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='pagedetails',
            old_name='seo_meta_keywords',
            new_name='seo_keywords',
        ),
        migrations.RenameField(
            model_name='pagedetails',
            old_name='seo_meta_link',
            new_name='seo_link',
        ),
    ]
