# Generated by Django 4.2.5 on 2025-06-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_address_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
