# Generated by Django 4.2.5 on 2025-09-07 05:57

import common.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagesAdministration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services_page_title', models.CharField(max_length=100, unique=True)),
                ('publish', models.BooleanField(default=False)),
                ('pageType', models.CharField(blank=True, max_length=100, null=True)),
                ('page_url', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('service_postion', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternative_text', models.CharField(blank=True, max_length=255, null=True)),
                ('serviceID', models.CharField(max_length=100)),
                ('services_page_title', models.CharField(max_length=100)),
                ('feature_title', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('services_page_url', models.CharField(blank=True, max_length=100, null=True)),
                ('services_feature_position', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pagesAdministration.pagedetails')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_features',
            },
        ),
        migrations.CreateModel(
            name='ServiceAccordion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternative_text', models.CharField(blank=True, max_length=255, null=True)),
                ('serviceID', models.CharField(max_length=100)),
                ('services_page_title', models.CharField(max_length=100)),
                ('accordion_title', models.CharField(blank=True, max_length=100, null=True)),
                ('accordion_sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('accordion_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('services_description_position', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion', to='pagesAdministration.pagedetails')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_accordions',
            },
        ),
    ]
