# Generated by Django 4.2.5 on 2025-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0002_remove_serviceaccordion_alternitivetext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccordion',
            name='services_description_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='services_feature_position',
            field=models.IntegerField(default=0),
        ),
    ]
