# Generated by Django 4.2.5 on 2024-06-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerAndIntro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerandintro',
            name='moreLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
