# Generated by Django 4.2.5 on 2025-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerAndIntro', '0003_alter_bannerandintro_originalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerandintro',
            name='contentType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
