# Generated by Django 4.2.5 on 2025-05-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisementlist',
            old_name='description',
            new_name='advertisement_description',
        ),
    ]
