# Generated by Django 4.2.5 on 2025-08-30 13:38

import common.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='alternitivetext',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='originalname',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='original_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.file_upload_path),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
