# Generated by Django 4.2.5 on 2025-03-19 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
