# Generated by Django 4.2.5 on 2025-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_themes', '0002_alter_themes_created_by_alter_themes_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
