# Generated by Django 4.2.5 on 2025-09-04 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowHideComponents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('componentName', models.CharField(max_length=500)),
                ('visibility', models.BooleanField(default=True)),
                ('pageType', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'show_hide_components',
                'unique_together': {('componentName', 'pageType')},
            },
        ),
    ]
