# Generated by Django 4.2.5 on 2025-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showHideComponents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showhidecomponents',
            name='componentName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='showhidecomponents',
            unique_together={('componentName', 'pageType')},
        ),
    ]
