# Generated by Django 4.2.5 on 2025-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showHideComponents', '0002_alter_showhidecomponents_componentname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showhidecomponents',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
