# Generated by Django 4.2.5 on 2025-08-27 16:35

import common.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.file_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternative_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_description', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.CharField(blank=True, max_length=100, null=True)),
                ('Views', models.CharField(blank=True, max_length=100, null=True)),
                ('Downloads', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('imageDimension', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('video_WebURL', models.URLField(blank=True, null=True)),
                ('video_id', models.CharField(blank=True, max_length=50)),
                ('video_thumbnail_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_gallery',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.file_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternative_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_description', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.CharField(blank=True, max_length=100, null=True)),
                ('Views', models.CharField(blank=True, max_length=100, null=True)),
                ('Downloads', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('imageDimension', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image_WebURL', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_gallery',
            },
        ),
    ]
