# Generated by Django 4.2.5 on 2024-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAndVideoGallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageandvideo',
            name='Downloads',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imageandvideo',
            name='Views',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imageandvideo',
            name='likes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
