# Generated by Django 4.2.5 on 2025-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAndVideoGallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='alternitivetext',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='alternitivetext',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
