# Generated by Django 4.2.5 on 2024-04-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageAndVideoGallery', '0002_alter_imageandvideo_downloads_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imageAndVideo',
            new_name='imageAndVideoGallery',
        ),
    ]
