# Generated by Django 4.2.5 on 2025-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAndVideoGallery', '0005_alter_imageandvideogallery_originalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageandvideogallery',
            name='image_WebURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
