# Generated by Django 4.2.5 on 2025-09-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_title', models.CharField(blank=True, max_length=100, null=True)),
                ('address_dr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('emailid', models.CharField(blank=True, max_length=100, null=True)),
                ('emailid_2', models.CharField(blank=True, max_length=100, null=True)),
                ('emailid_3', models.CharField(blank=True, max_length=100, null=True)),
                ('phonen_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phonen_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('phonen_number_3', models.CharField(blank=True, max_length=100, null=True)),
                ('address_position', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address_list',
            },
        ),
    ]
