# Generated by Django 4.2.5 on 2024-03-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslist',
            name='defaultAddress',
            field=models.BooleanField(default=False),
        ),
    ]
