# Generated by Django 4.2.5 on 2024-03-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressList', '0002_addresslist_defaultaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresslist',
            name='defaultAddress',
        ),
        migrations.AddField(
            model_name='addresslist',
            name='address_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
