# Generated by Django 4.2.5 on 2024-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressList', '0003_remove_addresslist_defaultaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslist',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addresslist',
            name='emailid_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addresslist',
            name='emailid_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addresslist',
            name='phonen_number_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
